mi_postgres:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DEV_HOST') }}"
      port: "{{ env_var('DBT_DEV_PORT') | int }}"
      user: "{{ env_var('DBT_DEV_USER') }}"
      pass: "{{ env_var('DBT_DEV_PASS') }}"
      dbname: "{{ env_var('DBT_DEV_DBNAME') }}"
      schema: "{{ env_var('DBT_DEV_SCHEMA') }}"

    prod:
      type: postgres
      threads: 1 
      host: prod-host.meiro.io
      port: 5432
      user: prod_user
      pass: prod_password
      dbname: prod_dbname
      schema: prod_schema

  target: dev
